// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/*
	// C++ 
	FGameplayTagContainer TagContainer;
	TagContainer.AddTag(ZfInventoryTags::WeaponTypes::Weapon_Staff);
	FGameplayTag WeaponStaffTag = ZfInventoryTags::WeaponTypes::Weapon_Staff;

	// Blueprint
	FGameplayTag MinhaTagDaBlueprint = FGameplayTag::RequestGameplayTag("MinhaTag.Tag.MinhaTag");
	FGameplayTagContainer MeuTagContainerComTagDaBlueprint;
	MeuTagContainerComTagDaBlueprint.AddTag(FGameplayTag::RequestGameplayTag("MinhaTag.Tag.MinhaTag"));
*/

namespace ZfEquipmentTags
{
	namespace EquipmentSlots
	{
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_None)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_None_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_MainHand)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_MainHand_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_OffHand)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_OffHand_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Head)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Head_1)

		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Chest)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Chest_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Legs)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Legs_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Feet_1)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Feet_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Hands_1)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Hands_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Cape_1)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Cape_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Backpack_1)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Backpack_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Ring)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Ring_1)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Ring_2)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Necklace)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Necklace_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Pickaxe)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Pickaxe_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Axe)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Axe_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Shovel)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Shovel_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_FishingRod)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_FishingRod_1)
		
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Consumable)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Consumable_1)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Consumable_2)
		ZF8DMOVING_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Slot_Consumable_3)
	}
}