;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayEffect.Type.AttributeSet.Progression.AvailablePoints",NewTagName="GameplayEffect.Type.AttributeSet.Progression.AttributePoints")
+GameplayTagList=(Tag="GameplayEffect.Type.AttributeSet.MainAttribute.Strength",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Type.AttributeSet.Progression.AttributePoints",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Type.Strength",DevComment="")

